# Generated by Django 3.1.7 on 2021-03-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Катерогия')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Загловок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('quote', models.CharField(max_length=250, verbose_name='Цитата')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m', verbose_name='Фото')),
                ('publish', models.BooleanField(verbose_name='Публиковано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='News.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('create_date',),
            },
        ),
    ]
