# Generated by Django 3.1.7 on 2021-03-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=80, null=True, verbose_name='Вид ссылки на категорию'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=80, null=True, verbose_name='Вид ссылки'),
        ),
    ]
