# Generated by Django 3.1.7 on 2021-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20210304_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=80, verbose_name='Вид ссылки на категорию'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=80, verbose_name='Вид ссылки'),
        ),
    ]
